### PR TITLE
Make the count a public var

### PR DESCRIPTION
**Pull request by marijnschilling**
Oh no forgot to make it public 🙈

### CODE REVIEW

**Comment by elland** [comment]
@marijnschilling does the extension need to be public as well? I think so. 🙈 sorry about this btw.

**Comment by marijnschilling** [comment]
Make all the things public! Yeah we all overlooked it 🤔... This is not being checked for in all the ways the pods are being checked (unit test, lint thing etc.) We should put something in the pod creating flow that catches this... But what!?

**Comment by elland** [comment]
Yeah, we need a testing module outside of the scope of the app, so we can test for access as well. Just having to test for access makes you more aware of this.

**Comment by elland** [comment]
Nice, looks good. Thanks for catching this. 🚢

**Comment by 3lvis** [comment]
Duh!

**Comment by 3lvis** [comment]
Thanks!

**Comment by elland** [comment]
How to dolan on Github?!

**Comment by 3lvis** [comment]
screen shot 2016-09-08 at 10 20 02 am

**Pull request merged**
