### PR TITLE
Move collection helpers from SweetFoundation

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by elland** [comment]
Should it be `enumeratedWithNext` or `enumerateWithNext` now?

**Comment by 3lvis** [comment]
Maybe neither? Just have it as 

``` swift
for (current, next) in someArray.enumerate() {
    if current == 2 {
        XCTAssert(next == 3)
    }
    break
}
```

**Comment by 3lvis** [comment]
Looks like Swift 3 likes `enumerated`

**Comment by 3lvis** [comment]
What about

``` swift
for (current, next) in someArray.enumeratedWithCurrentAndNext() {
    XCTAssert(current == 1)
    XCTAssert(next == 2)
    break
}
```

**Comment by elland** [comment]
Looks good to me.

**Pull request merged**
