### PR TITLE
Added String method to pad it to conform to base64 length.

### PR DESCRIPTION
**Pull request by elland**
What do you think?

### CODE REVIEW

**Comment by 3lvis** [comment]
Could you expand on how you're using this? What's the use case?

**Comment by elland** [comment]
I thought the title was quite self-explanatory. It adds the necessary padding to base64 strings if they are non-padded. 🤔

**Comment by 3lvis** [comment]
@Elland of course it does that, but in which case do you need this?

**Comment by elland** [comment]
What do you mean? Please be more specific in your questions. This is used when a base64-encoded string is sent without its padding and you need to add the padding back. 🤔

**Comment by 3lvis** [comment]
@Elland I think I understand now. Sounds too specific to be here. I would go for just keeping it inside your project.

**Comment by 3lvis** [comment]
Rephrasing my question: Why do you need to do that, wouldn't your base64 generator add the padding to it?

**Comment by elland** [comment]
My base64 generator is the system one. It does add padding. But other platforms might not. I don't see how this is project specific. Any project that deals with API calls and base64 where we don't control the full stack is subject to this "problem".

**Comment by 3lvis** [comment]
>My base64 generator is the system one. It does add padding. But other platforms might not.

So you aren't even using this method yourself?

**Comment by elland** [comment]
Of course I am. Server code for one of my projects transmits base64 strings without padding.

**Comment by 3lvis** [comment]
That makes it even more clear that it's probably something that you want to keep in your project. Seems like a workaround for an issue that your server is having, not something common in the iOS world like adding `count` to an `enum` for example.

**Comment by elland** [comment]
No, this makes it clear that this is a common thing. Base64 padding can be omitted. This is not a server bug, this is from the API design specs.

**Comment by 3lvis** [comment]
@Elland I'm still not sure if we should have this here, could you elaborate on other cases besides the one that you're providing?

**Comment by 3lvis** [comment]
@Elland Let me know when this is ready. Seems like a few changes are still coming :)

**Comment by elland** [comment]
I think I have to move this to Foundation first. 😭 `Data` initialisers are somehow not available without it. So odd.

**Comment by elland** [comment]
Moved to https://github.com/UseSweet/SweetFoundation/pull/18.

**Pull request closed without merging**
