### PR TITLE
Add simple function to retrieve date as ISO string

### PR DESCRIPTION
**Pull request by elland**
As requested  #10.

### CODE REVIEW

**Comment by elland** [comment]
@marijnschilling is that what you had in mind? Do you need something more customisable?

**Comment by 3lvis** [comment]
Unit tests! 💥

**Comment by 3lvis** [comment]
screen shot 2016-09-21 at 15 04 12

**Comment by elland** [comment]
Travis's UNIX date differs from OS X? WTH.

**Comment by 3lvis** [comment]
This feature needs Foundation. Closing since it doesn't belong to this repo.

**Pull request closed without merging**
